### ISSUE TITLE
[Enhancements] video player.

### ISSUE THREAD

**Issue by gaminglnk** [DevanAbinaya/Ani-Moopa#17]
I must say that this anime web app is surely one of the best open source projects I've seen.
Really nice work appreciate it, especially the Anilist integration. <hr/>
There are some video player enhancements I would like to mention, as it's the only thing that's a little bit off the theme I suppose.

### **Is your feature request related to a problem? Please describe.**
Yes and No. The requested feature is needed to provide a better experience to user.

### **Describe the solution you'd like**
I am talking some enhancements to the video player to make it's experience more appealing.
The requested features are :
- Double tap to skip and rewind `10` seconds.
- Change player icons to something smooth.
- Change player font to something other.

### **Additional context**
Just, the needed one is `double tap to skip/rewind`

**Comment by DevanAbinaya** [comment]
I'm not sure if I can add a double tap function to the player due to certain limitations. But what I can do is making a button to skip 10/5 seconds to forward/rewind the video. I'll look into this in a couple days.

Thanks for the suggestions!

**Comment by DevanAbinaya** [comment]
I've added forward/backward button to the player. Sorry that it took so long only for adding buttons I just got time to do it today. Thanks for your patience.
