### ISSUE TITLE
[Enhancements] add preview Thumbnails.

### ISSUE THREAD

**Issue by gaminglnk** [DevanAbinaya/Ani-Moopa#22]
Pardon me, as I am unable to contribute directly as not having the required devices right now.

Just wanting the vtt thumbnail support as vtt preview is provided by Zoro, also Art Player supports it using the plugin.

Thanks

**Comment by DevanAbinaya** [comment]
I will if I can, but there's no thumbnail returned from zoro. I know there was subtitle there but somehow there's no thumbnail now.
You can check this link :
```
https://api.consumet.org/meta/anilist/watch/kaguya-sama-love-is-war-season-2-23$episode$802$sub?provider=zoro
```

**Comment by gaminglnk** [comment]
Oh I see, now thumbnails aren't showing up.
My bad.
