### ISSUE TITLE
VIdeo doesnt display or load

### ISSUE THREAD

**Issue by chitrakshbotwala** [DevanAbinaya/Ani-Moopa#25]
so i deployed this project for personal use and whenever i try to view a video it is just stuc at buffering it couldnt load the video , it just loads episodes that it . Kindly help me with it please

**Comment by DevanAbinaya** [comment]
have put all the requirement inside the .env file?

**Comment by DevanAbinaya** [comment]
also what provider did you use to watch the video?

**Comment by chitrakshbotwala** [comment]
gogoanime

**Comment by chitrakshbotwala** [comment]
yes i have put all the requirements leaving the proxy part i didnt
understand how to do that

**Comment by DevanAbinaya** [comment]
can you give me the anime and episode id?

**Comment by chitrakshbotwala** [comment]
> also what provider did you use to watch the video?

also do i need to put .env variables in the API part like do i need to fill up the env variables for consumet , if yes kindly help me with where i can find them

**Comment by chitrakshbotwala** [comment]
> can you give me the anime and episode id?

its not only with a single anime its with every anime i try to watch not just me even my friend who tried to .

NOTE : i redeployed the app i am not talking about your version (MOOPA.live)

**Comment by DevanAbinaya** [comment]
> > also what provider did you use to watch the video?
> 
> also do i need to put .env variables in the API part like do i need to fill up the env variables for consumet , if yes kindly help me with where i can find them

The .env file should look like this :
```bash
CLIENT_ID=12345
CLIENT_SECRET=just paste the secret here
GRAPHQL_ENDPOINT=https://graphql.anilist.co <-- no need to change
NEXTAUTH_SECRET='run this cmd (openssl rand -base64 32)'
NEXTAUTH_URL=https://your.domain.com/ <-- if its local then 'http://localhost:3000/'
PROXY_URI=https://proxy.domain.com/ <--- if you have proxy, this proxy is for zoro and enime provider, gogo doesn't need this
API_URI=https://api.consumet.org <--- don't put '/' at the end this can cause problems
```

**Comment by himanshu8443** [comment]
CORS error may be

**Comment by DevanAbinaya** [comment]
also check this part again
```bash
API_URI=https://api.consumet.org <--- don't put '/' at the end this can cause problems
```

**Comment by DevanAbinaya** [comment]
> CORS error may be

shouldn't be an issue, I put cf worker for proxy there and it's public

**Comment by chitrakshbotwala** [comment]
> > > also what provider did you use to watch the video?
> > 
> > 
> > also do i need to put .env variables in the API part like do i need to fill up the env variables for consumet , if yes kindly help me with where i can find them
> 
> The .env file should look like this :
> 
> ```shell
> CLIENT_ID=12345
> CLIENT_SECRET=just paste the secret here
> GRAPHQL_ENDPOINT=https://graphql.anilist.co <-- no need to change
> NEXTAUTH_SECRET='run this cmd (openssl rand -base64 32)'
> NEXTAUTH_URL=https://your.domain.com/ <-- if its local then 'http://localhost:3000/'
> PROXY_URI=https://proxy.domain.com/ <--- if you have proxy, this proxy is for zoro and enime provider, gogo doesn't need this
> API_URI=https://api.consumet.org <--- don't put '/' at the end this can cause problems
> ```

also i didnt use proxy neither was i trying to watch enime or zoro i tried it on gogo and didnt work

**Comment by chitrakshbotwala** [comment]
> can you send the console log?

the api or the app?

**Comment by DevanAbinaya** [comment]
> > can you send the console log?
> 
> the api or the app?

the app, on the watch page

**Comment by chitrakshbotwala** [comment]
> > > can you send the console log?
> > 
> > 
> > the api or the app?
> 
> the app, on the watch page

ok

**Comment by chitrakshbotwala** [comment]
![image](https://github.com/DevanAbinaya/Ani-Moopa/assets/68012660/2f8d8c35-0339-4158-be32-dfffae16dbf2) 2
![image](https://github.com/DevanAbinaya/Ani-Moopa/assets/68012660/f61a44c9-525b-4fac-8864-10b5e7af77ba) 1

**Comment by chitrakshbotwala** [comment]
![Uploading image.png…]()
current

**Comment by DevanAbinaya** [comment]
umm I mean this console
![image](https://github.com/DevanAbinaya/Ani-Moopa/assets/97084324/1a7064ef-1971-4fb9-b478-c4fe08432e17)

**Comment by chitrakshbotwala** [comment]
![image](https://github.com/DevanAbinaya/Ani-Moopa/assets/68012660/8508bce2-a80d-4855-ab5d-fa4558655388)
it is still on the buffer part its been an hour

**Comment by chitrakshbotwala** [comment]
> umm I mean this console ![image](https://user-images.githubusercontent.com/97084324/251774938-1a7064ef-1971-4fb9-b478-c4fe08432e17.png)

oh ok

**Comment by chitrakshbotwala** [comment]
![image](https://github.com/DevanAbinaya/Ani-Moopa/assets/68012660/ae4c4f51-fcd8-4a7c-959f-b702fc416ad6)
there you go

**Comment by chitrakshbotwala** [comment]
![image](https://github.com/DevanAbinaya/Ani-Moopa/assets/68012660/2fa3da17-9b10-49bd-95bd-d8b73b39ceec)
better image and here are the logs

**Comment by DevanAbinaya** [comment]
yup found it, you shouldn't touch the url here
![image](https://github.com/DevanAbinaya/Ani-Moopa/assets/97084324/1a7b136b-87b2-457c-8374-d454ee2facdc)

**Comment by chitrakshbotwala** [comment]
> yup found it, you shouldn't touch the url here ![image](https://user-images.githubusercontent.com/97084324/251775966-1a7b136b-87b2-457c-8374-d454ee2facdc.png)

didnt get it did i change it up and messed it ? ive been bug hunting since yesterday

**Comment by DevanAbinaya** [comment]
yes, cause that's not a real url doesn't it?
but if you want to host your own proxy instance you can use this cf worker its easy to setup
https://github.com/Gratenes/m3u8CloudflareWorkerProxy

**Comment by chitrakshbotwala** [comment]
> yes, cause that's not a real url doesn't it? but if you want to host your own proxy instance you can use this cf worker its easy to setup https://github.com/Gratenes/m3u8CloudflareWorkerProxy

oh ok so i just replace it with cors.moopa.live?

**Comment by DevanAbinaya** [comment]
> oh ok so i just replace it with cors.moopa.live?

yup if you don't want to host anything, use this cors.moopa.my.id
*not .live

**Comment by chitrakshbotwala** [comment]
> > oh ok so i just replace it with cors.moopa.live?
> 
> yup if you don't want to host anything, use this cors.moopa.my.id *not .live

ok and thankyou so much for helping me out , you made a wonderful project .

**Comment by chitrakshbotwala** [comment]
> > > oh ok so i just replace it with cors.moopa.live?
> > 
> > 
> > yup if you don't want to host anything, use this cors.moopa.my.id *not .live
> 
> ok and thankyou so much for helping me out , you made a wonderful project .

it just started working thankyou so much , yaay 💀

**Comment by DevanAbinaya** [comment]
> > ok and thankyou so much for helping me out , you made a wonderful project .
> 
> it just started working thankyou so much , yaay 💀

Great!, glad to hear that.

**Comment by DevanAbinaya** [comment]
> > yup if you don't want to host anything, use this cors.moopa.my.id *not .live
> 
> ok and thankyou so much for helping me out , you made a wonderful project .

not a problem, I'm happy to help :). and since its working imma close this issue now

if you have anymore question just dm me on discord its in the readme file <3
