### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by TheGrapeJuice** [DevanAbinaya/Ani-Moopa#26]
getting this error when trying to run my own instance
![test](https://github.com/DevanAbinaya/Ani-Moopa/assets/102010764/c96f947e-8a43-4c59-9210-cc40794bfdee)

something with i.reduce it seems, any fix?

**Comment by chitrakshbotwala** [comment]
This error occurs when we call the reduce() method on a value that is not an array. To solve the error, make sure to only call the reduce method on arrays or conditionally check if the value is an array before calling the method

**Comment by DevanAbinaya** [comment]
please pull the code, and restart dev. I already made some changes. should be fixed now

**Comment by TheGrapeJuice** [comment]
thanks :)
